services:
  - type: web
    name: pos-backend
    runtime: node
    plan: free
    buildCommand: npm install && cd ../frontend && npm install && npm run build && cd ../backend && mkdir -p frontend && rm -rf frontend/dist && cp -r ../frontend/dist frontend/dist
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://andrescuesta19.github.io,https://sistema-ventas-pos-aeka.onrender.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
    healthCheckPath: /api/health
